### ISSUE TITLE
Долатать docs под основной стенд

### ISSUE THREAD

**Issue by martis-git** [feature-sliced/wiki#46]
![image](https://user-images.githubusercontent.com/42924400/110642526-263c6f00-81c4-11eb-94ea-22a338536a09.png)

**Comment by martis-git** [comment]
В gh же:

![image](https://user-images.githubusercontent.com/42924400/110642645-410ee380-81c4-11eb-9195-6cf6222bc4aa.png)

**Comment by martis-git** [comment]
Сейм проблема

![image](https://user-images.githubusercontent.com/42924400/111876932-f7877b00-89b1-11eb-9664-73a5bc7172ee.png)

**Comment by martis-git** [comment]
Т.е. как будто `<details>` секции коряво отображаются

**Comment by martis-git** [comment]
Такая же проблема и с отображением `h2` + `<hr/>`

![image](https://user-images.githubusercontent.com/42924400/111966264-c4ef9680-8b07-11eb-8879-3c63bc8f8e6f.png)
![image](https://user-images.githubusercontent.com/42924400/111966277-ca4ce100-8b07-11eb-9421-30a805c9e52c.png)

**Comment by martis-git** [comment]
Думаю в целом надо посмотреть на особенности выбранного рендерера `md => html`

**Comment by martis-git** [comment]
@karina-drummer обычный md похоже стенд тоже не переваривает))

![image](https://user-images.githubusercontent.com/42924400/115996509-3b405680-a5e8-11eb-859d-aed68f514bd4.png)

**Comment by karina-drummer** [comment]
> Такая же проблема и с отображением `h2` + `<hr/>`
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/42924400/111966264-c4ef9680-8b07-11eb-8879-3c63bc8f8e6f.png)
> 
> ![image](https://user-images.githubusercontent.com/42924400/111966277-ca4ce100-8b07-11eb-9421-30a805c9e52c.png)
> 
> 

В Markdown есть свои h2 и hr

**Comment by karina-drummer** [comment]
> @karina-drummer обычный md похоже стенд тоже не переваривает))
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/42924400/115996509-3b405680-a5e8-11eb-859d-aed68f514bd4.png)
> 
> 

Генераторы доки решат проблему, думаю

**Comment by martis-git** [comment]
Скорее всего будет пофикшено через docusaurus.io
